services:
  bot:
    build: .
    container_name: scribot_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Указываем путь к директории с базой данных
      - DB_DIR=/app/data
      # Указываем путь к директории для логов LLM
      - LLM_LOG_DIR=/app/logs
    volumes:
      # Монтируем директорию с базой данных, чтобы она сохранялась между запусками
      - ./data:/app/data
      # Монтируем директорию для логов LLM
      - ./logs:/app/logs
    working_dir: /app
    # Убеждаемся, что контейнер не завершается при ошибках
    stdin_open: true
    tty: true

